name: Build and deploy Python app to Azure Web App - MyfirstApp

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python version
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Setup build dependencies
        run: sudo apt-get install -y unixodbc-dev gcc g++ python3-dev

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_849B65DE0FB2455DB4F583DCD210A12D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A59F0BE0CF6A4B76853D995AE9EFF882 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D5C803D4F134FBCB7CE211190294FB1 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: MyfirstApp
          package: .
