name: Build and deploy Python app to Azure Web App - MyfirstApp

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install build dependencies
        run: sudo apt-get install -y build-essential unixodbc-dev gcc g++ python3-dev

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_849B65DE0FB2455DB4F583DCD210A12D }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5D5C803D4F134FBCB7CE71190294FB1 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A59F08E0CF6A4876853D995AE9EFF882 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'MyfirstApp'
          package: .
